name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify requirements file
        run: ls -l requirements.txt || echo "requirements.txt is missing!"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "requirements.txt not found. Skipping dependency installation."
          fi

      - name: Run tests with coverage
        run: |
          pytest --cov=calculator --cov-report=term-missing

      - name: Lint code with Pylint
        run: |
          pip install pylint
          pylint calculator --fail-under=8
